// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaReservas.Infraestructura.Persistencia;

#nullable disable

namespace PlataformaReservas.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoDatos))]
    partial class ContextoDatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nombre");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_slug");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("zona_horaria");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Politicas", "PlataformaReservas.Dominio.Entidades.Empresa.Politicas#PoliticasReserva", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AntelacionMaximaDias")
                                .HasColumnType("integer")
                                .HasColumnName("antelacion_maxima_dias");

                            b1.Property<int>("AntelacionMinimaMinutos")
                                .HasColumnType("integer")
                                .HasColumnName("antelacion_minima_minutos");

                            b1.Property<int>("IntervaloHuecosMinutos")
                                .HasColumnType("integer")
                                .HasColumnName("intervalo_huecos_minutos");
                        });

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Activa")
                        .HasDatabaseName("ix_empresas_activa");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_empresas_categoria_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_slug");

                    b.HasIndex("Ciudad", "CategoriaId")
                        .HasDatabaseName("ix_empresas_ciudad_categoria_id");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.ExcepcionHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profesional_id");

                    b.HasKey("Id")
                        .HasName("pk_excepciones_horario");

                    b.HasIndex("ProfesionalId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("ix_excepciones_horario_profesional_id_fecha");

                    b.ToTable("excepciones_horario", (string)null);
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profesional_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Intervalo", "PlataformaReservas.Dominio.Entidades.Horario.Intervalo#IntervaloHorario", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly>("HoraFin")
                                .HasColumnType("time without time zone")
                                .HasColumnName("hora_fin");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time without time zone")
                                .HasColumnName("hora_inicio");
                        });

                    b.HasKey("Id")
                        .HasName("pk_horarios");

                    b.HasIndex("ProfesionalId", "DiaSemana")
                        .HasDatabaseName("ix_horarios_profesional_id_dia_semana");

                    b.ToTable("horarios", (string)null);
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.MiembroEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_miembros_empresa");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_miembros_empresa_usuario_id");

                    b.HasIndex("EmpresaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_miembros_empresa_empresa_id_usuario_id");

                    b.ToTable("miembros_empresa", (string)null);
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Profesional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_profesionales");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_profesionales_empresa_id");

                    b.ToTable("profesionales", (string)null);
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DuracionAplicadaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_aplicada_minutos");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cancelacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_cliente");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PrecioAplicado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_aplicado");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profesional_id");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("servicio_id");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono_cliente");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Franja", "PlataformaReservas.Dominio.Entidades.Reserva.Franja#FranjaHoraria", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("FinUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fin_utc");

                            b1.Property<DateTime>("InicioUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio_utc");
                        });

                    b.HasKey("Id")
                        .HasName("pk_reservas");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_reservas_empresa_id");

                    b.HasIndex("ProfesionalId")
                        .HasDatabaseName("ix_reservas_profesional_id");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_reservas_servicio_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_reservas_usuario_id");

                    b.ToTable("reservas", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservas_franja", "fin_utc > inicio_utc");
                        });
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int?>("AntelacionMaximaDias")
                        .HasColumnType("integer")
                        .HasColumnName("antelacion_maxima_dias");

                    b.Property<int?>("AntelacionMinimaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("antelacion_minima_minutos");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int?>("IntervaloHuecosMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_huecos_minutos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("pk_servicios");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_servicios_empresa_id");

                    b.ToTable("servicios", null, t =>
                        {
                            t.HasCheckConstraint("ck_servicios_duracion", "duracion_minutos > 0");

                            t.HasCheckConstraint("ck_servicios_precio", "precio >= 0");
                        });
                });

            modelBuilder.Entity("PlataformaReservas.Infraestructura.Identidad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PlataformaReservas.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PlataformaReservas.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("PlataformaReservas.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PlataformaReservas.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Empresa", b =>
                {
                    b.HasOne("PlataformaReservas.Dominio.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empresas_categorias_categoria_id");
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.ExcepcionHorario", b =>
                {
                    b.HasOne("PlataformaReservas.Dominio.Entidades.Profesional", null)
                        .WithMany("Excepciones")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excepciones_horario_profesionales_profesional_id");
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Horario", b =>
                {
                    b.HasOne("PlataformaReservas.Dominio.Entidades.Profesional", null)
                        .WithMany("Horarios")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horarios_profesionales_profesional_id");
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.MiembroEmpresa", b =>
                {
                    b.HasOne("PlataformaReservas.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_miembros_empresa_empresas_empresa_id");

                    b.HasOne("PlataformaReservas.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_miembros_empresa_asp_net_users_usuario_id");
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Profesional", b =>
                {
                    b.HasOne("PlataformaReservas.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profesionales_empresas_empresa_id");

                    b.OwnsMany("PlataformaReservas.Dominio.Entidades.ProfesionalServicio", "_servicios", b1 =>
                        {
                            b1.Property<Guid>("ProfesionalId")
                                .HasColumnType("uuid")
                                .HasColumnName("profesional_id");

                            b1.Property<Guid>("ServicioId")
                                .HasColumnType("uuid")
                                .HasColumnName("servicio_id");

                            b1.HasKey("ProfesionalId", "ServicioId")
                                .HasName("pk_profesional_servicio");

                            b1.HasIndex("ServicioId")
                                .HasDatabaseName("ix_profesional_servicio_servicio_id");

                            b1.ToTable("profesional_servicio", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProfesionalId")
                                .HasConstraintName("fk_profesional_servicio_profesionales_profesional_id");

                            b1.HasOne("PlataformaReservas.Dominio.Entidades.Servicio", null)
                                .WithMany()
                                .HasForeignKey("ServicioId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_profesional_servicio_servicios_servicio_id");
                        });

                    b.Navigation("_servicios");
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Reserva", b =>
                {
                    b.HasOne("PlataformaReservas.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_empresas_empresa_id");

                    b.HasOne("PlataformaReservas.Dominio.Entidades.Profesional", null)
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_profesionales_profesional_id");

                    b.HasOne("PlataformaReservas.Dominio.Entidades.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_servicios_servicio_id");

                    b.HasOne("PlataformaReservas.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_asp_net_users_usuario_id");
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Servicio", b =>
                {
                    b.HasOne("PlataformaReservas.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_servicios_empresas_empresa_id");
                });

            modelBuilder.Entity("PlataformaReservas.Dominio.Entidades.Profesional", b =>
                {
                    b.Navigation("Excepciones");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
